name: Build

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          cd ${{github.workspace}}\utils
          .\build.bat
      - uses: actions/upload-artifact@v2.3.0
        with:
          name: artefatos
          path: ${{github.workspace}}\build\hmri.exe

  ubuntu:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          cd ${{github.workspace}}/utils
          ./build.sh
      - uses: actions/download-artifact@v2.1.0
        with:
          name: artefatos
          path: ${{github.workspace}}/build/hmri.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: hrm-interpreter
          path: ${{github.workspace}}/build/hmri*
