name: Build

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - run: ./utils/build.bat

      - uses: actions/upload-artifact@v2.3.0
        with:
          name: artefatos
          path: /build/hmri.exe

  ubuntu:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - run: ./utils/build.sh

      - uses: actions/download-artifact@v2.1.0
        with:
          name: artefatos
          path: /build/hmri.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: hrm-interpreter
          path: /build/hmri*
